### ISSUE TITLE
Sorry, our server must be overwhelmed. 

### ISSUE THREAD

**Issue by marcyshieh** [wpinvestigative/arcos-api#5]
I was able to obtain pharm_latlon() data but afterward, could not access any more of the data.

I kept getting the following error:

_Sorry, our server must be overwhelmed. Try again in a little bit. If it persists, let us know at https://github.com/wpinvestigative/arcos/issues_

I'm not sure if anyone else has encountered similar issues. I've tried using a different key and waiting a few minutes then trying again. Does anyone have any tips?

**Comment by andrewbtran** [comment]
Which function?

**Comment by marcyshieh** [comment]
I realized that I forgot to indicate county when I used the total_pharmacies_county(). It was my mistake.
